-- =============================================================================
-- myDropbox database schema
-- -----------------------------------------------------------------------------
-- Run this once in your Supabase project: Dashboard -> SQL Editor -> New query,
-- paste this whole file, and click "Run".
--
-- It creates the tables, Row-Level Security (RLS) policies, and the private
-- Storage bucket the app needs. RLS is what keeps each user's files private:
-- every query is automatically filtered to the logged-in user (auth.uid()).
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------

-- Folders form a tree via parent_id (NULL parent = top level / "My Files").
create table if not exists public.folders (
  id         uuid primary key default gen_random_uuid(),
  owner_id   uuid not null references auth.users (id) on delete cascade,
  parent_id  uuid references public.folders (id) on delete cascade,
  name       text not null,
  created_at timestamptz not null default now()
);

create index if not exists folders_owner_parent_idx
  on public.folders (owner_id, parent_id);

-- Files reference the blob stored in Storage via storage_path.
create table if not exists public.files (
  id           uuid primary key default gen_random_uuid(),
  owner_id     uuid not null references auth.users (id) on delete cascade,
  folder_id    uuid references public.folders (id) on delete cascade,
  name         text not null,
  storage_path text not null,
  size         bigint not null default 0,
  mime_type    text,
  created_at   timestamptz not null default now()
);

create index if not exists files_owner_folder_idx
  on public.files (owner_id, folder_id);

-- A share is a public, token-addressable pointer to one file. The signed_url
-- is generated by the owner (who has read access) at share-creation time and
-- lets anonymous visitors download without any server code.
create table if not exists public.shares (
  id         uuid primary key default gen_random_uuid(),
  token      uuid not null unique default gen_random_uuid(),
  owner_id   uuid not null references auth.users (id) on delete cascade,
  file_id    uuid not null references public.files (id) on delete cascade,
  file_name  text not null,
  mime_type  text,
  size       bigint not null default 0,
  signed_url text not null,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null
);

create index if not exists shares_token_idx on public.shares (token);
create index if not exists shares_owner_idx on public.shares (owner_id);

-- ---------------------------------------------------------------------------
-- Row-Level Security
-- ---------------------------------------------------------------------------

alter table public.folders enable row level security;
alter table public.files   enable row level security;
alter table public.shares  enable row level security;

-- Owners have full control over their own folders.
drop policy if exists "own folders" on public.folders;
create policy "own folders" on public.folders
  for all using (auth.uid() = owner_id) with check (auth.uid() = owner_id);

-- Owners have full control over their own files.
drop policy if exists "own files" on public.files;
create policy "own files" on public.files
  for all using (auth.uid() = owner_id) with check (auth.uid() = owner_id);

-- Owners manage their own shares...
drop policy if exists "own shares" on public.shares;
create policy "own shares" on public.shares
  for all using (auth.uid() = owner_id) with check (auth.uid() = owner_id);

-- ...but ANYONE (including anonymous visitors) may read a share row. This is
-- what powers public share links. Only non-sensitive fields live here, and the
-- token is an unguessable UUID.
drop policy if exists "public read shares" on public.shares;
create policy "public read shares" on public.shares
  for select using (true);

-- ---------------------------------------------------------------------------
-- Storage bucket + policies
-- ---------------------------------------------------------------------------

-- Private bucket: objects are not publicly listable/readable. Access happens
-- through signed URLs, which the owner generates for themselves or for shares.
insert into storage.buckets (id, name, public)
values ('files', 'files', false)
on conflict (id) do nothing;

-- Each user's blobs live under a top-level folder named after their user id,
-- e.g. "<uid>/<uuid>-report.pdf". These policies restrict every storage
-- operation to objects inside the caller's own "<uid>/" prefix.
drop policy if exists "own objects read"   on storage.objects;
drop policy if exists "own objects insert" on storage.objects;
drop policy if exists "own objects delete" on storage.objects;

create policy "own objects read" on storage.objects
  for select using (
    bucket_id = 'files' and (storage.foldername(name))[1] = auth.uid()::text
  );

create policy "own objects insert" on storage.objects
  for insert with check (
    bucket_id = 'files' and (storage.foldername(name))[1] = auth.uid()::text
  );

create policy "own objects delete" on storage.objects
  for delete using (
    bucket_id = 'files' and (storage.foldername(name))[1] = auth.uid()::text
  );
